apiVersion: apps/v1
kind: Deployment
metadata:
  name: iweblens-deployment
  labels:
    app: iweblens
spec:
  replicas: 5
  selector:
    matchLabels:
      app: iweblens
  template:
    metadata:
      labels:
        app: iweblens
    spec:
      containers:
      - name: iweblens
        image: haoxucode/iweblens_app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "0.5"
            memory: "512Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"
