apiVersion: v1
kind: Service
metadata:
  name: iweblens-service
  labels:
    app: iweblens
spec:
  selector:
    app: iweblens
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31000
    port: 8080
    targetPort: 5000